spring.application.name=businessplatform
spring.datasource.url=jdbc:mysql://localhost:3306/business_platform
spring.datasource.username=root
spring.datasource.password=Akhil@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.jwt.secret=change_this_to_a_long_random_string_at_least_32_characters_long
app.jwt.expiration-ms=86400000

management.endpoints.web.exposure.include=health,info